# Generated by Django 5.1.2 on 2024-10-20 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('country', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='atualizado_em', verbose_name='Atualizado em')),
                ('name', models.CharField(db_column='nome', max_length=255, verbose_name='Nome')),
                ('image', models.URLField(db_column='imagem', verbose_name='Imagem')),
                ('ingredients', models.TextField(db_column='ingredientes', verbose_name='Ingredientes')),
                ('preparation', models.TextField(db_column='preparacao', verbose_name='Preparação')),
                ('status', models.BooleanField(db_column='status', default=True, verbose_name='Status')),
                ('category_id', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Categoria')),
                ('country_id', models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.CASCADE, to='country.country', verbose_name='País')),
                ('created_by', models.ForeignKey(blank=True, db_column='id_criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, db_column='id_atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'db_table': 'tb_receita',
            },
        ),
    ]
