# Generated by Django 5.1.2 on 2024-11-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_userrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, db_column='descricao', null=True, verbose_name='Descrição'),
        ),
    ]
