# Generated by Django 5.1.2 on 2024-11-16 17:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrecipe',
            unique_together={('user_id', 'recipe_id')},
        ),
    ]
